### ISSUE TITLE
error after starting the bot

### ISSUE THREAD

**Issue by yikes101** [trinhvv/trading-analysis-bot#1]
Hi there,

I am currently getting the following error, maybe you are able to help/assists me.

```
/root/.local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cur.execute("SELECT chat_id FROM users")
psycopg2.ProgrammingError: relation "users" does not exist
LINE 1: SELECT chat_id FROM users
                            ^

Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cur.execute("SELECT chat_id FROM users")
psycopg2.ProgrammingError: relation "users" does not exist
LINE 1: SELECT chat_id FROM users
```

**Comment by trinhvv** [comment]
You need to create a database first to get DB_NAME, DB_PASSWORD, etc, then follow the guide in the READ_ME.
The database is mainly used to manage user access and collect their chat_id. 
You can delete or comment out any code related to database.

**Comment by gusleig** [comment]
Hi, Im stuck at the same issue. why I would delete or comment out code related to database and the bot still works? Sorry I didnt unerstand what you mean here.

**Comment by trinhvv** [comment]
If you already create a database, you need to create the table named 'users' before running the code.
You can delete every code related to the database in the script 'bot.py' and it will work because it is only for user access control.
